options:
	debug: false
	
	prefix: <gold>[&aFeudalism<gold>]<r>
	debugPrefix: <gold>[<yellow>Debug<gold>]<r>
	
	warn: <gold>[&aFeudalism<gold>] <yellow>WARNING:<light red>
	err: <gold>[&aFeudalism<gold>] <red>ERROR:<light red>
	MaterialWood: birch plank, oak plank or spruce plank
	MaterialClay: clay block, light gray clay, purple clay, gray clay or black clay
	MaterialStone: smooth brick, stone, upside-down double stone slab, double stone slab, decorated brick, cracked brick or cobble
	
on right click:
	display hologram "Click" at player's location for 10 second
	if player is holding an arrow:
		shoot an arrow at speed 0.75
		if gamemode of player isn't creative:
			remove an arrow from player
	else if player is holding an egg:
		cancel event
		make the player shoot an egg at speed 0.1
	else if player is holding a snowball:
		cancel event
		make the player shoot a snowball at speed 1
		

On Projectile Hit:
	set {_loc} to event-location
	
	If projectile is a snowball:
		delete projectile
		play "HORSE_WOOD" to shooter at volume 1.5
		Set {_radius} to 1
		Set {_block str} to 1
		set {_explosive} to "weak"
		
		set block at {_loc} to wood button
		wait 2 seconds
		set block at {_loc} to air
		create a safe explosion of force 4 at the event-location
		play "ZOMBIE_WOODBREAK" to shooter at volume 0.5
	Else if projectile is an arrow:
		delete projectile
		play "HORSE_JUMP" to shooter at volume 1.5
		Set {_radius} to 4
		Set {_block str} to 2
		set {_explosive} to "moderate"
		
		set block at {_loc} to stone button
		wait 4 seconds
		set block at {_loc} to air
		create a safe explosion of force 3 at the event-location
		play "ZOMBIE_WOODBREAK" to shooter at volume 1
	Else if projectile is an egg:
		delete projectile
		play "ZOMBIE_WOOD" to shooter at volume 1.5
		Set {_radius} to 5
		Set {_block str} to 4
		set {_explosive} to "powerful"
		
		set block at {_loc} to flower pot
		wait 5 seconds
		set block at {_loc} to air
		create a safe explosion of force 10 at the event-location
		play "ZOMBIE_WOODBREAK" to shooter at volume 1.5
	Loop blocks in radius {_radius} around event-location:
		Loop-block is {@MaterialWood} or {@MaterialClay} or {@MaterialStone}
		if loop-block is {@MaterialWood}:
			set {_material} to "wood"
			If loop-block is Birch plank:
				Set {_health} to 3
			Else if loop-block is oak plank:
				Set {_health} to 2
			else:
				Set {_health} to 1
		else if loop-block is {@MaterialClay}:
			set {_material} to "clay"
			If loop-block is clay block:
				Set {_health} to 5
			Else if loop-block is light gray clay:
				Set {_health} to 4
			Else if loop-block is purple clay:
				Set {_health} to 3
			Else if loop-block is gray clay:
				Set {_health} to 2
			else:
				Set {_health} to 1
		else if loop-block is {@MaterialStone}:
			set {_material} to "stone"
			if loop-block is upside-down double stone slab:
				Set {_health} to 7
			Else if loop-block is double stone slab:
				Set {_health} to 6
			Else if loop-block is stone:
				Set {_health} to 5
			else If loop-block is smooth brick:
				Set {_health} to 4
			Else if loop-block is decorated brick:
				Set {_health} to 3
			Else if loop-block is cracked brick:
				Set {_health} to 2
			Else:
				Set {_health} to 1
		set {_distance} to distance between loop-block and event-location
		If {_distance} is less than 0.76:
			Set {_dmg} to {_block str}
		Else if {_explosive} is "weak":
			if {_material} is "wood":
				Set {_dmg} to round({_block Str} - {_distance } - 1)
		Else if {_explosive} is "moderate":
			if {_material} is "stone":
				Set {_dmg} to round(1 - {_distance } - 1)
			else:
				Set {_dmg} to round({_block Str} - {_distance } - 1)
		else:
			Set {_dmg} to round({_block Str} - {_distance } - 1)
		{_dmg} is greater than 0
		Remove {_dmg} from {_health}
		#(convert block here)
		If {_health} is less than 1:
			Set loop-block to air
		Else If {_material} is "wood":
			if {_health} is 2:
				Set loop-block to oak plank 
			Else if {_health} is 1:
				Set loop-block to spruce plank 
			Else:
				Message "{@err} something wrong in explosion! Wood"
		Else If {_material} is "clay":
			if {_health} is 4:
				Set loop-block to light gray clay
			Else if {_health} is 3:
				Set loop-block to purple clay
			Else if {_health} is 2:
				Set loop-block to gray clay
			Else if {_health} is 1:
				Set loop-block to black clay
			Else:
				Message "{@err} something wrong in explosion! Clay"
		Else If {_material} is "stone":
			if {_health} is 6:
				Set loop-block to double stone slab
			Else if {_health} is 5:
				Set loop-block to stone
			Else if {_health} is 4:
				Set loop-block to smooth brick
			Else if {_health} is 3:
				Set loop-block to decorated brick
			Else if {_health} is 2:
				Set loop-block to cracked brick
			Else if {_health} is 1:
				Set loop-block to cobble
			Else:
				Message "{@err} something wrong in explosion! Clay"
		